---
- project:
    templates:
      - build-openstack-docs-pti
    check:
      jobs:
        - build-openstack-api-ref
        - build-openstack-releasenotes
        - flock-devstack-metal
        - openstack-tox-linters
        - openstack-tox-pep8
    gate:
      jobs:
        - build-openstack-api-ref
        - build-openstack-releasenotes
        - flock-devstack-metal
        - openstack-tox-linters
        - openstack-tox-pep8
    post:
      jobs:
        - publish-stx-api-ref
        - publish-stx-tox
        - publish-stx-releasenotes

- job:
    name: flock-devstack-metal
    parent: flock-devstack-base-min
    required-projects:
      - openstack/barbican
      - openstack/python-barbicanclient
      - starlingx/fault
      - starlingx/integ
      - starlingx/nfv
      - starlingx/update
    vars:
      tox_envlist: functional
      devstack_services:
        # StarlingX services
        fm-common: true
        # fm-api: true
        # mtce: true
        mtce-compute: true
        mtce-control: true
        mtce-storage: true
        inventory-api: true
        inventory-conductor: true
        inventory-agent: true
        inventory-client: true
        fsmon: true
        hbs: true
        hwmon: true
        mtcalarm: true
        mtclog: true
        pmon: true
        rmon: true
      devstack_plugins:
        barbican: https://opendev.org/openstack/barbican
        fault: https:://opendev.org/starlingx/fault
        integ: https://opendev.org/starlingx/integ
        metal: https:://opendev.org/starlingx/metal
        # nfv: https:://opendev.org/starlingx/nfv
        update: https:://opendev.org/starlingx/update
