---
- project:
    templates:
      - build-openstack-docs-pti
    check:
      jobs:
        - build-openstack-api-ref
        - build-openstack-releasenotes
        - flock-devstack-metal
        - openstack-tox-linters
        - openstack-tox-pep8
    gate:
      jobs:
        - build-openstack-api-ref
        - build-openstack-releasenotes
        - flock-devstack-metal
        - openstack-tox-linters
        - openstack-tox-pep8
    post:
      jobs:
        - publish-stx-api-ref
        - publish-stx-tox
        - publish-stx-releasenotes

- job:
    name: flock-devstack-metal
    parent: flock-devstack-base
    required-projects:
      - openstack/barbican
      - openstack/python-barbicanclient
      - openstack/stx-fault
      - openstack/stx-integ
      - openstack/stx-nfv
      - openstack/stx-update
    vars:
      tox_envlist: functional
      devstack_services:
        # StarlingX services
        fm-common: true
        # fm-api: true
        # mtce: true
        mtce-compute: true
        mtce-control: true
        mtce-storage: true
        inventory-api: true
        inventory-conductor: true
        inventory-agent: true
        inventory-client: true
        fsmon: true
        hbs: true
        hwmon: true
        mtcalarm: true
        mtclog: true
        pmon: true
        rmon: true
      devstack_plugins:
        barbican: https://git.openstack.org/openstack/barbican
        stx-fault: https:://git.starlingx.io/stx-fault
        stx-integ: https://git.starlingx.io/stx-integ
        stx-metal: https:://git.starlingx.io/stx-metal
        stx-nfv: https:://git.starlingx.io/stx-nfv
        stx-update: https:://git.starlingx.io/stx-update
