---
virtual_media_iso:
    dcloud1:
        bmc_address: <bmc ip address>
        bmc_username: <bmc username>
        bmc_password: <bmc password - base64 encoded >
        image: <url address, port and path to image>
    dcloud2:
        bmc_address: <bmc ip address>
        bmc_username: <bmc username>
        bmc_password: <bmc password - base64 encoded>
        image: <url address, port and path to image>
